// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using myAPI.Data;

#nullable disable

namespace myAPI.Migrations
{
    [DbContext(typeof(BaseHospital))]
    [Migration("20221117182907_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("myAPI.Models.Internamento", b =>
                {
                    b.Property<int>("InternamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Carater_Atendimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataAlta")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataInt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Leito")
                        .HasColumnType("TEXT");

                    b.Property<string>("Motivo_Encerramento")
                        .HasColumnType("TEXT");

                    b.Property<int>("PacienteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InternamentoId");

                    b.ToTable("Internamentos");
                });

            modelBuilder.Entity("myAPI.Models.Paciente", b =>
                {
                    b.Property<int>("PacienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cep")
                        .HasColumnType("TEXT");

                    b.Property<string>("Complemento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cpf")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataNasc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Logradouro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sexo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("PacienteId");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("myAPI.Models.Procedimento", b =>
                {
                    b.Property<int>("ProcedimentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo_Procedimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescProcedimento")
                        .HasColumnType("TEXT");

                    b.Property<int>("InternamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Medico")
                        .HasColumnType("TEXT");

                    b.Property<string>("MedicoCBO")
                        .HasColumnType("TEXT");

                    b.Property<int>("PacienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QtdProcedimento")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProcedimentoId");

                    b.ToTable("Procedimentos");
                });
#pragma warning restore 612, 618
        }
    }
}
